export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE'
export const UPLOAD_FILE_DONE = 'UPLOAD_FILE_DONE'
export const UPLOAD_FOLDER_FAILURE = 'UPLOAD_FOLDER_FAILURE'
export const UPLOAD_FOLDER_DONE = 'UPLOAD_FOLDER_DONE'
